<h1>Блог</h1>
<ul>
    <?php foreach ($list as $item) { ?>
        <li style="margin-bottom: 10px;">
            Пользователь: <?php echo $item['name']; ?><br>
            Сообщение: <?php echo $item['message']; ?><br>
            <?php if ($item["image"]) { ?>
                <img src="/<?php echo $item["image"]; ?>" alt="">
            <?php } ?>
            <?php if ($admin) { ?>
                <form action="/delete-message" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="blog_id" value="<?php echo $item['id']; ?>">
                    <input type="submit" value="Удалить">
                </form>
            <?php } ?>
        </li>
    <?php } ?>
</ul>

<form action="/add-message" method="post" enctype="multipart/form-data">
    Сообщение: <br>
    <textarea name="message" required cols="30" rows="10"></textarea> <br>
    <input type="file" name="image" accept="image/png, image/jpeg"> <br> <br>
    <input type="submit" value="Войти">
</form>

<?php
    if ($errors) {
        foreach ($errors as $error) {
            ?>
            <p style="color: red;"><?php echo $error; ?></p>
            <?php
        }
    }
?>