<h1>Регистрация:</h1>
<form action="/registration" method="post">
    Имя: <input type="text" name="name"> <br>
    Email: <input type="text" name="email"> <br>
    Пароль: <input type="password" name="password"> <br>
    Повторить пароль: <input type="password" name="confirm"> <br>
    <input type="submit" value="Зарегистрироваться">
</form>

<?php
    if ($errors) {
        foreach ($errors as $error) {
            ?>
            <p style="color: red;"><?php echo $error; ?></p>
            <?php
        }
    }
?>